/// <summary> OWASP Enterprise Security API .NET (ESAPI.NET)
/// 
/// This file is part of the Open Web Application Security Project (OWASP)
/// Enterprise Security API (ESAPI) project. For details, please see
/// http://www.owasp.org/esapi.
/// 
/// Copyright (c) 2008 - The OWASP Foundation
/// 
/// The ESAPI is published by OWASP under the LGPL. You should read and accept the
/// LICENSE before you use, modify, and/or redistribute this software.
/// 
/// </summary>
/// <author>  Alex Smolen <a href="http://www.foundstone.com">Foundstone</a>
/// </author>
/// <created>  2008 </created>

using System;
using NUnit.Framework;
using NUnit.Core;
using System.Collections;

namespace Owasp.Esapi.Test
{
    /// <summary> The Class AllTests
    /// 
    /// </summary>
    /// <author>  Alex Smolen (alex.smolen@foundstone.com)
    /// </author>        
    public class AllTests
    {
        /// <summary> Instantiates a new all tests.
        /// 
        /// </summary>
        public AllTests():base()
        {
        }

        /// <summary> Instantiates a new all tests.
        /// 
        /// </summary>
        /// <param name="testName">the test name
        /// </param>
        public AllTests(string testName)
        {
        }
        /// <summary> suite method automatically generated by NUnit module.
		/// 
		/// </summary>
		/// <returns> the test
		/// </returns>        
        [Suite]
		public static IEnumerable Suite
		{
		    get
            {
                
                System.Console.Out.WriteLine("INITIALIZING ALL TESTS");
			
			    // TODO: Update this
                //The following property must be set in order for the tests to find the resources directory
			    // You can set it here, or you can launch JUnit with the VM argument
			    //     -Dorg.owasp.espai.resources="/Users/...ESAPI/test/testresources"
			    System.Environment.SetEnvironmentVariable(SecurityConfiguration.RESOURCE_DIRECTORY, "C:/Users/.../ESAPI/test/testresources");
    			
			    ArrayList suite = new ArrayList();
                suite.Add(new Owasp.Esapi.Test.LoggerTest());
                suite.Add(new Owasp.Esapi.Test.UserTest());
                suite.Add(new Owasp.Esapi.Test.RandomizerTest());
                suite.Add(new Owasp.Esapi.Test.AccessControllerTest());
                suite.Add(new Owasp.Esapi.Test.HttpUtilitiesTest());
                suite.Add(new Owasp.Esapi.Test.ValidatorTest());
                suite.Add(new Owasp.Esapi.Test.EncryptorTest());
                suite.Add(new Owasp.Esapi.Test.IntrusionDetectorTest());
                suite.Add(new Owasp.Esapi.Test.AccessReferenceMapTest());
                suite.Add(new Owasp.Esapi.Test.ExecutorTest());
                suite.Add(new Owasp.Esapi.Test.EncoderTest());
                suite.Add(new Owasp.Esapi.Test.EncryptedPropertiesTest());
                suite.Add(new Owasp.Esapi.Test.AuthenticatorTest());
                suite.Add(new Owasp.Esapi.Test.Errors.EnterpriseSecurityExceptionTest());
			    return suite;
            }
        }		
    }
}
