//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owasp.Esapi.Swingset {
    
    
    public partial class Register {
        
        /// <summary>
        /// EsapiCreateUserWizard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CreateUserWizard EsapiCreateUserWizard;
        
        /// <summary>
        /// EsapiCreateUserWizardStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CreateUserWizardStep EsapiCreateUserWizardStep;
        
        /// <summary>
        /// EsapiCompleteWizardStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompleteWizardStep EsapiCompleteWizardStep;
    }
}
