//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owasp.Esapi.SampleWebApp {
    
    public partial class Login {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label UsernameLabel;
        protected System.Web.UI.WebControls.TextBox UsernameTextBox;
        protected System.Web.UI.WebControls.Label PasswordLabel;
        protected System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected System.Web.UI.WebControls.Button LoginButton;
    }
}
